### ISSUE TITLE
Bad parse for multiple defined env vars in line

### ISSUE THREAD

**Issue by jarekwg** [wizeline/travieso#8]
### Steps to reproduce
- Create a `.travis.yml` with mutliple env vars in one line:

```
env:
  - matrix:
      - TASK=general-tests SOMEOTHERVAR=7
      - TASK=flake8
  - global:
      - FOO=BAR
```
- Travis will read these as separate vars if they're separated by a space, but Travieso sets the task name to `(.+)`, which reads more than just the var

**Expected output:** task names: `[general-tests, flake8]`

**Actual output:** task names: `[general-tests SOMEOTHERVAR=7, flake8]`
### Metadata

**Travieso version:**: ae3a069f3fb2f3e7fed8839c8dfc17fc4df07e70

**Python version:**: 3.5.1

**Operating system:**: Mac
